dataset:
  root:    /ghome/group03/mcv/datasets/C5/KITTI-MOTS
  split:   val
 
model:
  type:   sam
  name:   facebook/sam-vit-huge
 
evaluation:
  type:         bbox_detection
  output_dir:   results/evaluation/bbox_detection_nano
  confidence:   0.5
  yolo_weights: yolo26n.pt  # omit to use yolo26x pretrained