dataset:
  root:    /ghome/group03/mcv/datasets/C5/KITTI-MOTS
  split:   val
 
model:
  type:   sam
  name:   facebook/sam-vit-huge
 
inference:
  type:         bbox_detection
  output_dir:   results/inference/bbox_detection
  confidence:   0.25
  # yolo_weights: /path/to/custom.pt  # omit to use yolo26x pretrained
  index_list : [400, 782, 2000]